#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 17 17:01:46 2019

@author: chansa
"""

def countdown(x):
    if x == 5:
        print ("Done")
        return
    else:
        print(x,"...")
        countdown(x-1)
        


countdown(10)

def power(num, pwr):
    if pwr == 0:
        return 1
    else:
        return num * power(num, pwr-1)
    


def factorial(num):
    if num == 0:
        return 1
    else:
        
        return num * factorial(num-1)

print("{} to the power of {} is {}".format(5, 3, power(5, 3)))
print("{} to the power of {} is {}".format(1, 5, power(1, 5)))
print("{} ! is {}".format(4, factorial(4)))
print("{} ! is {}".format(0, factorial(0)))